# Change these first
owner: kw214 # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository
user-agent: kw214
sites:
  - name: Github Trending Repo
    url: https://api.gitterapp.com/repositories
  - name: Github Trending Developer
    url: https://api.gitterapp.com/developers
  - name: Github Languages
    url: https://api.gitterapp.com/languages
  - name: Github Spoken Languages
    url: https://api.gitterapp.com/spoken_languages
  - name: Github Readme
    url: https://github.gitterapp.com/api/readme?owner=kw214&repo=kw214
  - name: Github Pinned
    url: https://github.gitterapp.com/api/pinned?username=kw214
  - name: Github Contributions
    url: https://github.gitterapp.com/api/contributions?username=kw214&from=2021-01-01&to=2021-12-31
  - name: Github Contributions(V2)
    url: https://github.gitterapp.com/api/v2/contributions?username=kw214&from=2021-01-01&to=2021-12-31

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: uptime.kimmy.me
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Uptime
  introTitle: "**Uptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/see/uptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
commitMessages:
  commitAuthorName: "kw214"
  commitAuthorEmail: "upcwangying@126.com"
